###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
"fullname": "admin admin", "email": "admin@admin.com", "password": "qwerty", "role":"0"
}

###
POST http://localhost:8080/api/users/auth
Content-Type: application/json

{
  "email": "uga.buga4@mail.com", "password": "qwerty"
}

###
POST http://localhost:8080/api/users/logout
Content-Type: application/json

{
}

###
GET http://localhost:8080/api/users/profile
Accept: application/json

###
GET http://localhost:8080/api/courses
Accept: application/json

###
GET http://localhost:8080/api/grades/2
Accept: application/json